// Client-supplied catalog. Confirm trade names and specifications before supply.
export const categories = [
  {
    "slug": "solvents",
    "name": "Solvents",
    "short": "Solvents",
    "number": "01",
    "description": "Explore our listed solvents and related materials, with origins and grades supplied by our team."
  },
  {
    "slug": "glycols",
    "name": "Glycols",
    "short": "Glycols",
    "number": "02",
    "description": "Monoethylene Glycol (MEG), Diethylene Glycol (DEG), Butyl Glycol, Propylene Glycol USP, and Propylene Glycol Technical."
  },
  {
    "slug": "industrial",
    "name": "Industrial Chemicals",
    "short": "Industrial",
    "number": "03",
    "description": "Acids, alkalis, carbon black, sulphur, and more."
  },
  {
    "slug": "technical",
    "name": "Technical Products",
    "short": "Technical",
    "number": "04",
    "description": "Technical agrochemical materials for professional business inquiries."
  },
  {
    "slug": "carbon",
    "name": "Carbon",
    "short": "Carbon",
    "number": "05",
    "description": "Carbon materials including Carbon Black N330 for industrial requirements."
  },
  {
    "slug": "other",
    "name": "Other Chemicals",
    "short": "Other chemicals",
    "number": "06",
    "description": "For additional chemical requirements, contact our team with your specification."
  }
];
export const retiredProductSlugs = ["t20"];
export const products = [
  {
    "slug": "xylene",
    "name": "Mix Xylene",
    "category": "solvents",
    "grade": "Confirm with our team",
    "purity": "Specification on request",
    "packaging": "On request",
    "origin": "Confirm with quotation",
    "needsConfirmation": false,
    "cas": "",
    "image": "/images/category-solvents.png",
    "imageLabel": "Illustrative category photograph",
    "description": "Mix Xylene is part of the Hussain & Co product list. Send your required specification, quantity, and destination for a quotation.",
    "applications": [],
    "moq": "Confirm with quotation",
    "sdsUrl": "",
    "tdsUrl": "",
    "featured": true,
    "order": 1
  },
  {
    "slug": "methanol-sabic",
    "name": "Methanol Sabic",
    "category": "solvents",
    "grade": "Confirm with our team",
    "purity": "Specification on request",
    "packaging": "On request",
    "origin": "Confirm with quotation",
    "needsConfirmation": false,
    "cas": "",
    "image": "/images/category-solvents.png",
    "imageLabel": "Illustrative category photograph",
    "description": "Methanol Sabic is part of the Hussain & Co product list. Send your required specification, quantity, and destination for a quotation.",
    "applications": [],
    "moq": "Confirm with quotation",
    "sdsUrl": "",
    "tdsUrl": "",
    "featured": false,
    "order": 2
  },
  {
    "slug": "dmf",
    "name": "Dimethylformamide (DMF)",
    "category": "solvents",
    "grade": "Confirm with our team",
    "purity": "Specification on request",
    "packaging": "On request",
    "origin": "Saudi Arabia / China",
    "needsConfirmation": false,
    "cas": "",
    "image": "/images/category-solvents.png",
    "imageLabel": "Illustrative category photograph",
    "description": "Dimethylformamide (DMF) is part of the Hussain & Co product list. Send your required specification, quantity, and destination for a quotation.",
    "applications": [],
    "moq": "Confirm with quotation",
    "sdsUrl": "",
    "tdsUrl": "",
    "featured": true,
    "order": 3
  },
  {
    "slug": "cyclohexanone",
    "name": "Cyclohexanone",
    "category": "solvents",
    "grade": "Confirm with our team",
    "purity": "Specification on request",
    "packaging": "Sealed / tanker",
    "origin": "Confirm with quotation",
    "needsConfirmation": false,
    "cas": "",
    "image": "/images/category-solvents.png",
    "imageLabel": "Illustrative category photograph",
    "description": "Cyclohexanone is part of the Hussain & Co product list. Send your required specification, quantity, and destination for a quotation.",
    "applications": [],
    "moq": "Confirm with quotation",
    "sdsUrl": "",
    "tdsUrl": "",
    "featured": false,
    "order": 4
  },
  {
    "slug": "chloroform",
    "name": "Chloroform",
    "category": "solvents",
    "grade": "Confirm with our team",
    "purity": "Specification on request",
    "packaging": "Tanker / sealed",
    "origin": "Russia",
    "needsConfirmation": false,
    "cas": "",
    "image": "/images/category-solvents.png",
    "imageLabel": "Illustrative category photograph",
    "description": "Chloroform is part of the Hussain & Co product list. Send your required specification, quantity, and destination for a quotation.",
    "applications": [],
    "moq": "Confirm with quotation",
    "sdsUrl": "",
    "tdsUrl": "",
    "featured": false,
    "order": 5
  },
  {
    "slug": "iso-butanol",
    "name": "ISO Butanol",
    "category": "solvents",
    "grade": "Confirm with our team",
    "purity": "Specification on request",
    "packaging": "On request",
    "origin": "Confirm with quotation",
    "needsConfirmation": false,
    "cas": "",
    "image": "/images/category-solvents.png",
    "imageLabel": "Illustrative category photograph",
    "description": "ISO Butanol is part of the Hussain & Co product list. Send your required specification, quantity, and destination for a quotation.",
    "applications": [],
    "moq": "Confirm with quotation",
    "sdsUrl": "",
    "tdsUrl": "",
    "featured": false,
    "order": 6
  },
  {
    "slug": "n-butanol",
    "name": "N-Butanol",
    "category": "solvents",
    "grade": "Confirm with our team",
    "purity": "Specification on request",
    "packaging": "On request",
    "origin": "Confirm with quotation",
    "needsConfirmation": false,
    "cas": "",
    "image": "/images/category-solvents.png",
    "imageLabel": "Illustrative category photograph",
    "description": "N-Butanol is part of the Hussain & Co product list. Send your required specification, quantity, and destination for a quotation.",
    "applications": [],
    "moq": "Confirm with quotation",
    "sdsUrl": "",
    "tdsUrl": "",
    "featured": false,
    "order": 7
  },
  {
    "slug": "ipa-99-9",
    "name": "Isopropyl Alcohol (IPA) 99.9%",
    "category": "solvents",
    "grade": "99.9%",
    "purity": "99.9%",
    "packaging": "On request",
    "origin": "Confirm with quotation",
    "needsConfirmation": false,
    "cas": "",
    "image": "/images/category-solvents.png",
    "imageLabel": "Illustrative category photograph",
    "description": "Isopropyl Alcohol (IPA) 99.9% is part of the Hussain & Co product list. Send your required specification, quantity, and destination for a quotation.",
    "applications": [],
    "moq": "Confirm with quotation",
    "sdsUrl": "",
    "tdsUrl": "",
    "featured": true,
    "order": 8
  },
  {
    "slug": "ipa-98",
    "name": "Isopropyl Alcohol (IPA) 98%",
    "category": "solvents",
    "grade": "98%",
    "purity": "98%",
    "packaging": "On request",
    "origin": "Confirm with quotation",
    "needsConfirmation": false,
    "cas": "",
    "image": "/images/category-solvents.png",
    "imageLabel": "Illustrative category photograph",
    "description": "Isopropyl Alcohol (IPA) 98% is part of the Hussain & Co product list. Send your required specification, quantity, and destination for a quotation.",
    "applications": [],
    "moq": "Confirm with quotation",
    "sdsUrl": "",
    "tdsUrl": "",
    "featured": false,
    "order": 9
  },
  {
    "slug": "ipa-96",
    "name": "Isopropyl Alcohol (IPA) 96%",
    "category": "solvents",
    "grade": "96%",
    "purity": "96%",
    "packaging": "On request",
    "origin": "Confirm with quotation",
    "needsConfirmation": false,
    "cas": "",
    "image": "/images/category-solvents.png",
    "imageLabel": "Illustrative category photograph",
    "description": "Isopropyl Alcohol (IPA) 96% is part of the Hussain & Co product list. Send your required specification, quantity, and destination for a quotation.",
    "applications": [],
    "moq": "Confirm with quotation",
    "sdsUrl": "",
    "tdsUrl": "",
    "featured": false,
    "order": 10
  },
  {
    "slug": "methyl-acetate",
    "name": "Methyl Acetate 99.9%",
    "category": "solvents",
    "grade": "99.9%",
    "purity": "99.9%",
    "packaging": "On request",
    "origin": "Confirm with quotation",
    "needsConfirmation": false,
    "cas": "",
    "image": "/images/category-solvents.png",
    "imageLabel": "Illustrative category photograph",
    "description": "Methyl Acetate 99.9% is part of the Hussain & Co product list. Send your required specification, quantity, and destination for a quotation.",
    "applications": [],
    "moq": "Confirm with quotation",
    "sdsUrl": "",
    "tdsUrl": "",
    "featured": false,
    "order": 11
  },
  {
    "slug": "mc",
    "name": "Methylene Chloride (MC)",
    "category": "solvents",
    "grade": "Confirm with our team",
    "purity": "Specification on request",
    "packaging": "On request",
    "origin": "China / Korea",
    "needsConfirmation": false,
    "cas": "",
    "image": "/images/category-solvents.png",
    "imageLabel": "Illustrative category photograph",
    "description": "Methylene Chloride (MC) is part of the Hussain & Co product list. Send your required specification, quantity, and destination for a quotation.",
    "applications": [],
    "moq": "Confirm with quotation",
    "sdsUrl": "",
    "tdsUrl": "",
    "featured": false,
    "order": 12
  },
  {
    "slug": "glacial-acetic-acid",
    "name": "Glacial Acetic Acid",
    "category": "solvents",
    "grade": "Confirm with our team",
    "purity": "Specification on request",
    "packaging": "On request",
    "origin": "Korea",
    "needsConfirmation": false,
    "cas": "",
    "image": "/images/category-solvents.png",
    "imageLabel": "Illustrative category photograph",
    "description": "Glacial Acetic Acid is part of the Hussain & Co product list. Send your required specification, quantity, and destination for a quotation.",
    "applications": [],
    "moq": "Confirm with quotation",
    "sdsUrl": "",
    "tdsUrl": "",
    "featured": false,
    "order": 13
  },
  {
    "slug": "cobalt-12",
    "name": "Cobalt 12%",
    "category": "solvents",
    "grade": "12%",
    "purity": "12%",
    "packaging": "On request",
    "origin": "Local / imported",
    "needsConfirmation": true,
    "cas": "",
    "image": "/images/category-solvents.png",
    "imageLabel": "Illustrative category photograph",
    "description": "Cobalt 12% is part of the Hussain & Co product list. Send your required specification, quantity, and destination for a quotation.",
    "applications": [],
    "moq": "Confirm with quotation",
    "sdsUrl": "",
    "tdsUrl": "",
    "featured": false,
    "order": 14
  },
  {
    "slug": "glycerine",
    "name": "Glycerine",
    "category": "solvents",
    "grade": "Confirm with our team",
    "purity": "Specification on request",
    "packaging": "On request",
    "origin": "Local / imported",
    "needsConfirmation": false,
    "cas": "",
    "image": "/images/category-solvents.png",
    "imageLabel": "Illustrative category photograph",
    "description": "Glycerine is part of the Hussain & Co product list. Send your required specification, quantity, and destination for a quotation.",
    "applications": [],
    "moq": "Confirm with quotation",
    "sdsUrl": "",
    "tdsUrl": "",
    "featured": false,
    "order": 15
  },
  {
    "slug": "np9",
    "name": "NP9",
    "category": "solvents",
    "grade": "Confirm with our team",
    "purity": "Specification on request",
    "packaging": "On request",
    "origin": "Thailand / Germany / China",
    "needsConfirmation": false,
    "cas": "",
    "image": "/images/category-solvents.png",
    "imageLabel": "Illustrative category photograph",
    "description": "NP9 is part of the Hussain & Co product list. Send your required specification, quantity, and destination for a quotation.",
    "applications": [],
    "moq": "Confirm with quotation",
    "sdsUrl": "",
    "tdsUrl": "",
    "featured": false,
    "order": 16
  },
  {
    "slug": "np15",
    "name": "NP 15",
    "category": "solvents",
    "grade": "Confirm with our team",
    "purity": "Specification on request",
    "packaging": "On request",
    "origin": "China",
    "needsConfirmation": false,
    "cas": "",
    "image": "/images/category-solvents.png",
    "imageLabel": "Illustrative category photograph",
    "description": "NP 15 is part of the Hussain & Co product list. Send your required specification, quantity, and destination for a quotation.",
    "applications": [],
    "moq": "Confirm with quotation",
    "sdsUrl": "",
    "tdsUrl": "",
    "featured": false,
    "order": 17
  },
  {
    "slug": "dop",
    "name": "DOP",
    "category": "solvents",
    "grade": "Confirm with our team",
    "purity": "Specification on request",
    "packaging": "On request",
    "origin": "Local / imported",
    "needsConfirmation": false,
    "cas": "",
    "image": "/images/category-solvents.png",
    "imageLabel": "Illustrative category photograph",
    "description": "DOP is part of the Hussain & Co product list. Send your required specification, quantity, and destination for a quotation.",
    "applications": [],
    "moq": "Confirm with quotation",
    "sdsUrl": "",
    "tdsUrl": "",
    "featured": false,
    "order": 18
  },
  {
    "slug": "formic-acid",
    "name": "Formic Acid",
    "category": "solvents",
    "grade": "Confirm with our team",
    "purity": "Specification on request",
    "packaging": "On request",
    "origin": "Confirm with quotation",
    "needsConfirmation": false,
    "cas": "",
    "image": "/images/category-solvents.png",
    "imageLabel": "Illustrative category photograph",
    "description": "Formic Acid is part of the Hussain & Co product list. Send your required specification, quantity, and destination for a quotation.",
    "applications": [],
    "moq": "Confirm with quotation",
    "sdsUrl": "",
    "tdsUrl": "",
    "featured": false,
    "order": 19
  },
  {
    "slug": "phenol",
    "name": "Phenol",
    "category": "solvents",
    "grade": "Confirm with our team",
    "purity": "Specification on request",
    "packaging": "On request",
    "origin": "Confirm with quotation",
    "needsConfirmation": false,
    "cas": "",
    "image": "/images/category-solvents.png",
    "imageLabel": "Illustrative category photograph",
    "description": "Phenol is part of the Hussain & Co product list. Send your required specification, quantity, and destination for a quotation.",
    "applications": [],
    "moq": "Confirm with quotation",
    "sdsUrl": "",
    "tdsUrl": "",
    "featured": false,
    "order": 20
  },
  {
    "slug": "white-spirit",
    "name": "White Spirit",
    "category": "solvents",
    "grade": "Confirm with our team",
    "purity": "Specification on request",
    "packaging": "On request",
    "origin": "Confirm with quotation",
    "needsConfirmation": false,
    "cas": "",
    "image": "/images/category-solvents.png",
    "imageLabel": "Illustrative category photograph",
    "description": "White Spirit is part of the Hussain & Co product list. Send your required specification, quantity, and destination for a quotation.",
    "applications": [],
    "moq": "Confirm with quotation",
    "sdsUrl": "",
    "tdsUrl": "",
    "featured": false,
    "order": 21
  },
  {
    "slug": "kerosene",
    "name": "Kerosene",
    "category": "solvents",
    "grade": "Confirm with our team",
    "purity": "Specification on request",
    "packaging": "On request",
    "origin": "Confirm with quotation",
    "needsConfirmation": false,
    "cas": "",
    "image": "/images/category-solvents.png",
    "imageLabel": "Illustrative category photograph",
    "description": "Kerosene is part of the Hussain & Co product list. Send your required specification, quantity, and destination for a quotation.",
    "applications": [],
    "moq": "Confirm with quotation",
    "sdsUrl": "",
    "tdsUrl": "",
    "featured": false,
    "order": 22
  },
  {
    "slug": "phosphoric-acid-75",
    "name": "Phosphoric Acid 75%",
    "category": "solvents",
    "grade": "75%",
    "purity": "75%",
    "packaging": "On request",
    "origin": "Confirm with quotation",
    "needsConfirmation": false,
    "cas": "",
    "image": "/images/category-solvents.png",
    "imageLabel": "Illustrative category photograph",
    "description": "Phosphoric Acid 75% is part of the Hussain & Co product list. Send your required specification, quantity, and destination for a quotation.",
    "applications": [],
    "moq": "Confirm with quotation",
    "sdsUrl": "",
    "tdsUrl": "",
    "featured": false,
    "order": 23
  },
  {
    "slug": "phosphoric-acid-85",
    "name": "Phosphoric Acid 85%",
    "category": "solvents",
    "grade": "85%",
    "purity": "85%",
    "packaging": "On request",
    "origin": "Confirm with quotation",
    "needsConfirmation": false,
    "cas": "",
    "image": "/images/category-solvents.png",
    "imageLabel": "Illustrative category photograph",
    "description": "Phosphoric Acid 85% is part of the Hussain & Co product list. Send your required specification, quantity, and destination for a quotation.",
    "applications": [],
    "moq": "Confirm with quotation",
    "sdsUrl": "",
    "tdsUrl": "",
    "featured": false,
    "order": 24
  },
  {
    "slug": "ethyal-glycol",
    "name": "Ethyal Glycol",
    "category": "solvents",
    "grade": "Confirm with our team",
    "purity": "Specification on request",
    "packaging": "On request",
    "origin": "Confirm with quotation",
    "needsConfirmation": true,
    "cas": "",
    "image": "/images/category-solvents.png",
    "imageLabel": "Illustrative category photograph",
    "description": "Ethyal Glycol is part of the Hussain & Co product list. Send your required specification, quantity, and destination for a quotation.",
    "applications": [],
    "moq": "Confirm with quotation",
    "sdsUrl": "",
    "tdsUrl": "",
    "featured": false,
    "order": 25
  },
  {
    "slug": "acrylic",
    "name": "Acrylic",
    "category": "solvents",
    "grade": "Confirm with our team",
    "purity": "Specification on request",
    "packaging": "On request",
    "origin": "Confirm with quotation",
    "needsConfirmation": true,
    "cas": "",
    "image": "/images/category-solvents.png",
    "imageLabel": "Illustrative category photograph",
    "description": "Acrylic is part of the Hussain & Co product list. Send your required specification, quantity, and destination for a quotation.",
    "applications": [],
    "moq": "Confirm with quotation",
    "sdsUrl": "",
    "tdsUrl": "",
    "featured": false,
    "order": 26
  },
  {
    "slug": "meg",
    "name": "Monoethylene Glycol (MEG)",
    "category": "glycols",
    "grade": "Confirm with our team",
    "purity": "Specification on request",
    "packaging": "On request",
    "origin": "Confirm with quotation",
    "needsConfirmation": false,
    "cas": "",
    "image": "/images/category-glycols.png",
    "imageLabel": "Illustrative category photograph",
    "description": "Monoethylene Glycol (MEG) is part of the Hussain & Co product list. Send your required specification, quantity, and destination for a quotation.",
    "applications": [],
    "moq": "Confirm with quotation",
    "sdsUrl": "",
    "tdsUrl": "",
    "featured": false,
    "order": 27
  },
  {
    "slug": "deg",
    "name": "Diethylene Glycol (DEG)",
    "category": "glycols",
    "grade": "Confirm with our team",
    "purity": "Specification on request",
    "packaging": "On request",
    "origin": "Confirm with quotation",
    "needsConfirmation": false,
    "cas": "",
    "image": "/images/category-glycols.png",
    "imageLabel": "Illustrative category photograph",
    "description": "Diethylene Glycol (DEG) is part of the Hussain & Co product list. Send your required specification, quantity, and destination for a quotation.",
    "applications": [],
    "moq": "Confirm with quotation",
    "sdsUrl": "",
    "tdsUrl": "",
    "featured": false,
    "order": 28
  },
  {
    "slug": "butyl-glycol",
    "name": "Butyl Glycol",
    "category": "glycols",
    "grade": "Confirm with our team",
    "purity": "Specification on request",
    "packaging": "On request",
    "origin": "China / Germany",
    "needsConfirmation": false,
    "cas": "",
    "image": "/images/category-glycols.png",
    "imageLabel": "Illustrative category photograph",
    "description": "Butyl Glycol is part of the Hussain & Co product list. Send your required specification, quantity, and destination for a quotation.",
    "applications": [],
    "moq": "Confirm with quotation",
    "sdsUrl": "",
    "tdsUrl": "",
    "featured": false,
    "order": 29
  },
  {
    "slug": "propylene-glycol-usp",
    "name": "Propylene Glycol USP",
    "category": "glycols",
    "grade": "USP",
    "purity": "USP",
    "packaging": "On request",
    "origin": "China",
    "needsConfirmation": false,
    "cas": "",
    "image": "/images/category-glycols.png",
    "imageLabel": "Illustrative category photograph",
    "description": "Propylene Glycol USP is part of the Hussain & Co product list. Send your required specification, quantity, and destination for a quotation.",
    "applications": [],
    "moq": "Confirm with quotation",
    "sdsUrl": "",
    "tdsUrl": "",
    "featured": false,
    "order": 30
  },
  {
    "slug": "propylene-glycol-technical",
    "name": "Propylene Glycol Technical",
    "category": "glycols",
    "grade": "Technical",
    "purity": "Technical",
    "packaging": "On request",
    "origin": "China",
    "needsConfirmation": false,
    "cas": "",
    "image": "/images/category-glycols.png",
    "imageLabel": "Illustrative category photograph",
    "description": "Propylene Glycol Technical is part of the Hussain & Co product list. Send your required specification, quantity, and destination for a quotation.",
    "applications": [],
    "moq": "Confirm with quotation",
    "sdsUrl": "",
    "tdsUrl": "",
    "featured": false,
    "order": 31
  },
  {
    "slug": "nitrosol",
    "name": "Nitrosol",
    "category": "industrial",
    "grade": "Confirm with our team",
    "purity": "Specification on request",
    "packaging": "On request",
    "origin": "Confirm with quotation",
    "needsConfirmation": true,
    "cas": "",
    "image": "/images/laboratory.jpg",
    "imageLabel": "Illustrative laboratory photograph",
    "description": "Nitrosol is part of the Hussain & Co product list. Send your required specification, quantity, and destination for a quotation.",
    "applications": [],
    "moq": "Confirm with quotation",
    "sdsUrl": "",
    "tdsUrl": "",
    "featured": false,
    "order": 32
  },
  {
    "slug": "potassium-carbonate",
    "name": "Potassium Carbonate",
    "category": "industrial",
    "grade": "Confirm with our team",
    "purity": "Specification on request",
    "packaging": "On request",
    "origin": "Confirm with quotation",
    "needsConfirmation": false,
    "cas": "",
    "image": "/images/laboratory.jpg",
    "imageLabel": "Illustrative laboratory photograph",
    "description": "Potassium Carbonate is part of the Hussain & Co product list. Send your required specification, quantity, and destination for a quotation.",
    "applications": [],
    "moq": "Confirm with quotation",
    "sdsUrl": "",
    "tdsUrl": "",
    "featured": false,
    "order": 33
  },
  {
    "slug": "potassium-hydroxide",
    "name": "Potassium Hydroxide",
    "category": "industrial",
    "grade": "Confirm with our team",
    "purity": "Specification on request",
    "packaging": "On request",
    "origin": "Confirm with quotation",
    "needsConfirmation": false,
    "cas": "",
    "image": "/images/laboratory.jpg",
    "imageLabel": "Illustrative laboratory photograph",
    "description": "Potassium Hydroxide is part of the Hussain & Co product list. Send your required specification, quantity, and destination for a quotation.",
    "applications": [],
    "moq": "Confirm with quotation",
    "sdsUrl": "",
    "tdsUrl": "",
    "featured": false,
    "order": 34
  },
  {
    "slug": "citric-acid",
    "name": "Citric Acid",
    "category": "industrial",
    "grade": "Mono / anhydrous",
    "purity": "Mono / anhydrous",
    "packaging": "On request",
    "origin": "Confirm with quotation",
    "needsConfirmation": false,
    "cas": "",
    "image": "/images/laboratory.jpg",
    "imageLabel": "Illustrative laboratory photograph",
    "description": "Citric Acid is part of the Hussain & Co product list. Send your required specification, quantity, and destination for a quotation.",
    "applications": [],
    "moq": "Confirm with quotation",
    "sdsUrl": "",
    "tdsUrl": "",
    "featured": true,
    "order": 35
  },
  {
    "slug": "boric-acid",
    "name": "Boric Acid",
    "category": "industrial",
    "grade": "Confirm with our team",
    "purity": "Specification on request",
    "packaging": "On request",
    "origin": "USA / Turkey",
    "needsConfirmation": false,
    "cas": "",
    "image": "/images/laboratory.jpg",
    "imageLabel": "Illustrative laboratory photograph",
    "description": "Boric Acid is part of the Hussain & Co product list. Send your required specification, quantity, and destination for a quotation.",
    "applications": [],
    "moq": "Confirm with quotation",
    "sdsUrl": "",
    "tdsUrl": "",
    "featured": false,
    "order": 36
  },
  {
    "slug": "sulphur",
    "name": "Sulphur Elemental",
    "category": "industrial",
    "grade": "Confirm with our team",
    "purity": "Specification on request",
    "packaging": "On request",
    "origin": "Confirm with quotation",
    "needsConfirmation": false,
    "cas": "",
    "image": "/images/laboratory.jpg",
    "imageLabel": "Illustrative laboratory photograph",
    "description": "Sulphur Elemental is part of the Hussain & Co product list. Send your required specification, quantity, and destination for a quotation.",
    "applications": [],
    "moq": "Confirm with quotation",
    "sdsUrl": "",
    "tdsUrl": "",
    "featured": false,
    "order": 37
  },
  {
    "slug": "carbon-black-n330",
    "name": "Carbon Black N330",
    "category": "carbon",
    "grade": "N330",
    "purity": "N330",
    "packaging": "On request",
    "origin": "Confirm with quotation",
    "needsConfirmation": false,
    "cas": "",
    "image": "/images/category-carbon.png",
    "imageLabel": "Illustrative category photograph",
    "description": "Carbon Black N330 is part of the Hussain & Co product list. Send your required specification, quantity, and destination for a quotation.",
    "applications": [],
    "moq": "Confirm with quotation",
    "sdsUrl": "",
    "tdsUrl": "",
    "featured": false,
    "order": 38
  },
  {
    "slug": "maleic-anhydrous",
    "name": "Maleic Anhydrous",
    "category": "industrial",
    "grade": "Confirm with our team",
    "purity": "Specification on request",
    "packaging": "On request",
    "origin": "Confirm with quotation",
    "needsConfirmation": true,
    "cas": "",
    "image": "/images/laboratory.jpg",
    "imageLabel": "Illustrative laboratory photograph",
    "description": "Maleic Anhydrous is part of the Hussain & Co product list. Send your required specification, quantity, and destination for a quotation.",
    "applications": [],
    "moq": "Confirm with quotation",
    "sdsUrl": "",
    "tdsUrl": "",
    "featured": false,
    "order": 39
  },
  {
    "slug": "pathalic-anhydrous",
    "name": "Pathalic Anhydrous",
    "category": "industrial",
    "grade": "Confirm with our team",
    "purity": "Specification on request",
    "packaging": "On request",
    "origin": "Confirm with quotation",
    "needsConfirmation": true,
    "cas": "",
    "image": "/images/laboratory.jpg",
    "imageLabel": "Illustrative laboratory photograph",
    "description": "Pathalic Anhydrous is part of the Hussain & Co product list. Send your required specification, quantity, and destination for a quotation.",
    "applications": [],
    "moq": "Confirm with quotation",
    "sdsUrl": "",
    "tdsUrl": "",
    "featured": false,
    "order": 40
  },
  {
    "slug": "fipronil",
    "name": "Fipronil 96%",
    "category": "technical",
    "grade": "96%",
    "purity": "96%",
    "packaging": "On request",
    "origin": "Confirm with quotation",
    "needsConfirmation": false,
    "cas": "",
    "image": "/images/category-technical.png",
    "imageLabel": "Illustrative category photograph",
    "description": "Fipronil 96% is part of the Hussain & Co product list. Send your required specification, quantity, and destination for a quotation.",
    "applications": [],
    "moq": "Confirm with quotation",
    "sdsUrl": "",
    "tdsUrl": "",
    "featured": false,
    "order": 41
  },
  {
    "slug": "emamectin",
    "name": "Emamectin",
    "category": "technical",
    "grade": "Confirm with our team",
    "purity": "Specification on request",
    "packaging": "On request",
    "origin": "Confirm with quotation",
    "needsConfirmation": false,
    "cas": "",
    "image": "/images/category-technical.png",
    "imageLabel": "Illustrative category photograph",
    "description": "Emamectin is part of the Hussain & Co product list. Send your required specification, quantity, and destination for a quotation.",
    "applications": [],
    "moq": "Confirm with quotation",
    "sdsUrl": "",
    "tdsUrl": "",
    "featured": false,
    "order": 42
  },
  {
    "slug": "monomehpo",
    "name": "Monomehpo",
    "category": "technical",
    "grade": "Confirm with our team",
    "purity": "Specification on request",
    "packaging": "On request",
    "origin": "Confirm with quotation",
    "needsConfirmation": true,
    "cas": "",
    "image": "/images/category-technical.png",
    "imageLabel": "Illustrative category photograph",
    "description": "Monomehpo is part of the Hussain & Co product list. Send your required specification, quantity, and destination for a quotation.",
    "applications": [],
    "moq": "Confirm with quotation",
    "sdsUrl": "",
    "tdsUrl": "",
    "featured": false,
    "order": 43
  },
  {
    "slug": "cartap",
    "name": "Cartap",
    "category": "technical",
    "grade": "Confirm with our team",
    "purity": "Specification on request",
    "packaging": "On request",
    "origin": "Confirm with quotation",
    "needsConfirmation": false,
    "cas": "",
    "image": "/images/category-technical.png",
    "imageLabel": "Illustrative category photograph",
    "description": "Cartap is part of the Hussain & Co product list. Send your required specification, quantity, and destination for a quotation.",
    "applications": [],
    "moq": "Confirm with quotation",
    "sdsUrl": "",
    "tdsUrl": "",
    "featured": false,
    "order": 44
  },
  {
    "slug": "cypermethrine",
    "name": "Cypermethrine",
    "category": "technical",
    "grade": "Confirm with our team",
    "purity": "Specification on request",
    "packaging": "On request",
    "origin": "Confirm with quotation",
    "needsConfirmation": true,
    "cas": "",
    "image": "/images/category-technical.png",
    "imageLabel": "Illustrative category photograph",
    "description": "Cypermethrine is part of the Hussain & Co product list. Send your required specification, quantity, and destination for a quotation.",
    "applications": [],
    "moq": "Confirm with quotation",
    "sdsUrl": "",
    "tdsUrl": "",
    "featured": false,
    "order": 45
  },
  {
    "slug": "aluminium-phosphide",
    "name": "Aluminium Phosphide",
    "category": "technical",
    "grade": "Confirm with our team",
    "purity": "Specification on request",
    "packaging": "On request",
    "origin": "Confirm with quotation",
    "needsConfirmation": false,
    "cas": "",
    "image": "/images/category-technical.png",
    "imageLabel": "Illustrative category photograph",
    "description": "Aluminium Phosphide is part of the Hussain & Co product list. Send your required specification, quantity, and destination for a quotation.",
    "applications": [],
    "moq": "Confirm with quotation",
    "sdsUrl": "",
    "tdsUrl": "",
    "featured": false,
    "order": 46
  },
  {
    "slug": "acetochlor",
    "name": "Acetochlor 95%",
    "category": "technical",
    "grade": "95%",
    "purity": "95%",
    "packaging": "On request",
    "origin": "Confirm with quotation",
    "needsConfirmation": false,
    "cas": "",
    "image": "/images/category-technical.png",
    "imageLabel": "Illustrative category photograph",
    "description": "Acetochlor 95% is part of the Hussain & Co product list. Send your required specification, quantity, and destination for a quotation.",
    "applications": [],
    "moq": "Confirm with quotation",
    "sdsUrl": "",
    "tdsUrl": "",
    "featured": false,
    "order": 47
  },
  {
    "slug": "azoxystrobin",
    "name": "Azoxystrobin 98%",
    "category": "technical",
    "grade": "98%",
    "purity": "98%",
    "packaging": "On request",
    "origin": "Confirm with quotation",
    "needsConfirmation": false,
    "cas": "",
    "image": "/images/category-technical.png",
    "imageLabel": "Illustrative category photograph",
    "description": "Azoxystrobin 98% is part of the Hussain & Co product list. Send your required specification, quantity, and destination for a quotation.",
    "applications": [],
    "moq": "Confirm with quotation",
    "sdsUrl": "",
    "tdsUrl": "",
    "featured": false,
    "order": 48
  },
  {
    "slug": "chlorfenpyr",
    "name": "Chlorfenpyr 98%",
    "category": "technical",
    "grade": "98%",
    "purity": "98%",
    "packaging": "On request",
    "origin": "Confirm with quotation",
    "needsConfirmation": true,
    "cas": "",
    "image": "/images/category-technical.png",
    "imageLabel": "Illustrative category photograph",
    "description": "Chlorfenpyr 98% is part of the Hussain & Co product list. Send your required specification, quantity, and destination for a quotation.",
    "applications": [],
    "moq": "Confirm with quotation",
    "sdsUrl": "",
    "tdsUrl": "",
    "featured": false,
    "order": 49
  },
  {
    "slug": "dimethmorp",
    "name": "Dimethmorp 98%",
    "category": "technical",
    "grade": "98%",
    "purity": "98%",
    "packaging": "On request",
    "origin": "Confirm with quotation",
    "needsConfirmation": true,
    "cas": "",
    "image": "/images/category-technical.png",
    "imageLabel": "Illustrative category photograph",
    "description": "Dimethmorp 98% is part of the Hussain & Co product list. Send your required specification, quantity, and destination for a quotation.",
    "applications": [],
    "moq": "Confirm with quotation",
    "sdsUrl": "",
    "tdsUrl": "",
    "featured": false,
    "order": 50
  },
  {
    "slug": "propiconazole",
    "name": "Propiconazole 95%",
    "category": "technical",
    "grade": "95%",
    "purity": "95%",
    "packaging": "On request",
    "origin": "Confirm with quotation",
    "needsConfirmation": false,
    "cas": "",
    "image": "/images/category-technical.png",
    "imageLabel": "Illustrative category photograph",
    "description": "Propiconazole 95% is part of the Hussain & Co product list. Send your required specification, quantity, and destination for a quotation.",
    "applications": [],
    "moq": "Confirm with quotation",
    "sdsUrl": "",
    "tdsUrl": "",
    "featured": false,
    "order": 51
  },
  {
    "slug": "agrasa",
    "name": "Agrasa",
    "category": "technical",
    "grade": "Confirm with our team",
    "purity": "Specification on request",
    "packaging": "On request",
    "origin": "Confirm with quotation",
    "needsConfirmation": true,
    "cas": "",
    "image": "/images/category-technical.png",
    "imageLabel": "Illustrative category photograph",
    "description": "Agrasa is part of the Hussain & Co product list. Send your required specification, quantity, and destination for a quotation.",
    "applications": [],
    "moq": "Confirm with quotation",
    "sdsUrl": "",
    "tdsUrl": "",
    "featured": false,
    "order": 52
  },
  {
    "slug": "pva-bp26-china",
    "name": "PVA Bp26 china",
    "category": "other",
    "grade": "Confirm with our team",
    "purity": "Specification on request",
    "packaging": "On request",
    "origin": "Confirm with quotation",
    "needsConfirmation": false,
    "cas": "",
    "image": "/images/other.png",
    "imageLabel": "Illustrative category photograph",
    "description": "PVA Bp26 china is part of the Hussain & Co product list. Send your required specification, quantity, and destination for a quotation.",
    "applications": [],
    "moq": "Confirm with quotation",
    "sdsUrl": "",
    "tdsUrl": "",
    "featured": false,
    "order": 53
  },
  {
    "slug": "cmc-china",
    "name": "CMC china",
    "category": "other",
    "grade": "Confirm with our team",
    "purity": "Specification on request",
    "packaging": "On request",
    "origin": "Confirm with quotation",
    "needsConfirmation": false,
    "cas": "",
    "image": "/images/other.png",
    "imageLabel": "Illustrative category photograph",
    "description": "CMC china is part of the Hussain & Co product list. Send your required specification, quantity, and destination for a quotation.",
    "applications": [],
    "moq": "Confirm with quotation",
    "sdsUrl": "",
    "tdsUrl": "",
    "featured": false,
    "order": 54
  },
  {
    "slug": "hec",
    "name": "HEC",
    "category": "other",
    "grade": "Confirm with our team",
    "purity": "Specification on request",
    "packaging": "On request",
    "origin": "Confirm with quotation",
    "needsConfirmation": false,
    "cas": "",
    "image": "/images/other.png",
    "imageLabel": "Illustrative category photograph",
    "description": "HEC is part of the Hussain & Co product list. Send your required specification, quantity, and destination for a quotation.",
    "applications": [],
    "moq": "Confirm with quotation",
    "sdsUrl": "",
    "tdsUrl": "",
    "featured": false,
    "order": 55
  },
  {
    "slug": "hpmc",
    "name": "HPMC",
    "category": "other",
    "grade": "Confirm with our team",
    "purity": "Specification on request",
    "packaging": "On request",
    "origin": "Confirm with quotation",
    "needsConfirmation": false,
    "cas": "",
    "image": "/images/other.png",
    "imageLabel": "Illustrative category photograph",
    "description": "HPMC is part of the Hussain & Co product list. Send your required specification, quantity, and destination for a quotation.",
    "applications": [],
    "moq": "Confirm with quotation",
    "sdsUrl": "",
    "tdsUrl": "",
    "featured": false,
    "order": 56
  },
  {
    "slug": "para-formaldehyde-saudia",
    "name": "Para formaldehyde saudia",
    "category": "other",
    "grade": "Confirm with our team",
    "purity": "Specification on request",
    "packaging": "On request",
    "origin": "Confirm with quotation",
    "needsConfirmation": false,
    "cas": "",
    "image": "/images/other.png",
    "imageLabel": "Illustrative category photograph",
    "description": "Para formaldehyde saudia is part of the Hussain & Co product list. Send your required specification, quantity, and destination for a quotation.",
    "applications": [],
    "moq": "Confirm with quotation",
    "sdsUrl": "",
    "tdsUrl": "",
    "featured": false,
    "order": 57
  },
  {
    "slug": "sodium-formate-taiwan",
    "name": "Sodium formate taiwan",
    "category": "other",
    "grade": "Confirm with our team",
    "purity": "Specification on request",
    "packaging": "On request",
    "origin": "Confirm with quotation",
    "needsConfirmation": false,
    "cas": "",
    "image": "/images/other.png",
    "imageLabel": "Illustrative category photograph",
    "description": "Sodium formate taiwan is part of the Hussain & Co product list. Send your required specification, quantity, and destination for a quotation.",
    "applications": [],
    "moq": "Confirm with quotation",
    "sdsUrl": "",
    "tdsUrl": "",
    "featured": false,
    "order": 58
  },
  {
    "slug": "sodium-hyrosulphite-90",
    "name": "Sodium Hyrosulphite 90%",
    "category": "other",
    "grade": "Confirm with our team",
    "purity": "Specification on request",
    "packaging": "On request",
    "origin": "Confirm with quotation",
    "needsConfirmation": false,
    "cas": "",
    "image": "/images/other.png",
    "imageLabel": "Illustrative category photograph",
    "description": "Sodium Hyrosulphite 90% is part of the Hussain & Co product list. Send your required specification, quantity, and destination for a quotation.",
    "applications": [],
    "moq": "Confirm with quotation",
    "sdsUrl": "",
    "tdsUrl": "",
    "featured": false,
    "order": 59
  },
  {
    "slug": "xanthum-gum-china",
    "name": "Xanthum gum china",
    "category": "other",
    "grade": "Confirm with our team",
    "purity": "Specification on request",
    "packaging": "On request",
    "origin": "Confirm with quotation",
    "needsConfirmation": false,
    "cas": "",
    "image": "/images/other.png",
    "imageLabel": "Illustrative category photograph",
    "description": "Xanthum gum china is part of the Hussain & Co product list. Send your required specification, quantity, and destination for a quotation.",
    "applications": [],
    "moq": "Confirm with quotation",
    "sdsUrl": "",
    "tdsUrl": "",
    "featured": false,
    "order": 60
  },
  {
    "slug": "chromic-acid",
    "name": "Chromic acid",
    "category": "other",
    "grade": "Confirm with our team",
    "purity": "Specification on request",
    "packaging": "On request",
    "origin": "Confirm with quotation",
    "needsConfirmation": false,
    "cas": "",
    "image": "/images/other.png",
    "imageLabel": "Illustrative category photograph",
    "description": "Chromic acid is part of the Hussain & Co product list. Send your required specification, quantity, and destination for a quotation.",
    "applications": [],
    "moq": "Confirm with quotation",
    "sdsUrl": "",
    "tdsUrl": "",
    "featured": false,
    "order": 61
  },
  {
    "slug": "oxalic-acid",
    "name": "Oxalic acid",
    "category": "other",
    "grade": "Confirm with our team",
    "purity": "Specification on request",
    "packaging": "On request",
    "origin": "Confirm with quotation",
    "needsConfirmation": false,
    "cas": "",
    "image": "/images/other.png",
    "imageLabel": "Illustrative category photograph",
    "description": "Oxalic acid is part of the Hussain & Co product list. Send your required specification, quantity, and destination for a quotation.",
    "applications": [],
    "moq": "Confirm with quotation",
    "sdsUrl": "",
    "tdsUrl": "",
    "featured": false,
    "order": 62
  },
  {
    "slug": "titanium-dioxide-r996",
    "name": "Titanium dioxide R996",
    "category": "other",
    "grade": "Confirm with our team",
    "purity": "Specification on request",
    "packaging": "On request",
    "origin": "Confirm with quotation",
    "needsConfirmation": false,
    "cas": "",
    "image": "/images/other.png",
    "imageLabel": "Illustrative category photograph",
    "description": "Titanium dioxide R996 is part of the Hussain & Co product list. Send your required specification, quantity, and destination for a quotation.",
    "applications": [],
    "moq": "Confirm with quotation",
    "sdsUrl": "",
    "tdsUrl": "",
    "featured": false,
    "order": 63
  },
  {
    "slug": "titanium-dioxide-6618",
    "name": "Titanium dioxide 6618",
    "category": "other",
    "grade": "Confirm with our team",
    "purity": "Specification on request",
    "packaging": "On request",
    "origin": "Confirm with quotation",
    "needsConfirmation": false,
    "cas": "",
    "image": "/images/other.png",
    "imageLabel": "Illustrative category photograph",
    "description": "Titanium dioxide 6618 is part of the Hussain & Co product list. Send your required specification, quantity, and destination for a quotation.",
    "applications": [],
    "moq": "Confirm with quotation",
    "sdsUrl": "",
    "tdsUrl": "",
    "featured": false,
    "order": 64
  },
  {
    "slug": "magnesium-sulphate",
    "name": "Magnesium sulphate",
    "category": "other",
    "grade": "Confirm with our team",
    "purity": "Specification on request",
    "packaging": "On request",
    "origin": "Confirm with quotation",
    "needsConfirmation": false,
    "cas": "",
    "image": "/images/other.png",
    "imageLabel": "Illustrative category photograph",
    "description": "Magnesium sulphate is part of the Hussain & Co product list. Send your required specification, quantity, and destination for a quotation.",
    "applications": [],
    "moq": "Confirm with quotation",
    "sdsUrl": "",
    "tdsUrl": "",
    "featured": false,
    "order": 65
  },
  {
    "slug": "magnese-sulphate",
    "name": "Magnese sulphate",
    "category": "other",
    "grade": "Confirm with our team",
    "purity": "Specification on request",
    "packaging": "On request",
    "origin": "Confirm with quotation",
    "needsConfirmation": false,
    "cas": "",
    "image": "/images/other.png",
    "imageLabel": "Illustrative category photograph",
    "description": "Magnese sulphate is part of the Hussain & Co product list. Send your required specification, quantity, and destination for a quotation.",
    "applications": [],
    "moq": "Confirm with quotation",
    "sdsUrl": "",
    "tdsUrl": "",
    "featured": false,
    "order": 66
  },
  {
    "slug": "copper-sulphate",
    "name": "Copper sulphate",
    "category": "other",
    "grade": "Confirm with our team",
    "purity": "Specification on request",
    "packaging": "On request",
    "origin": "Confirm with quotation",
    "needsConfirmation": false,
    "cas": "",
    "image": "/images/other.png",
    "imageLabel": "Illustrative category photograph",
    "description": "Copper sulphate is part of the Hussain & Co product list. Send your required specification, quantity, and destination for a quotation.",
    "applications": [],
    "moq": "Confirm with quotation",
    "sdsUrl": "",
    "tdsUrl": "",
    "featured": false,
    "order": 67
  },
  {
    "slug": "nitrosol",
    "name": "Nitrosol",
    "category": "other",
    "grade": "Confirm with our team",
    "purity": "Specification on request",
    "packaging": "On request",
    "origin": "Confirm with quotation",
    "needsConfirmation": false,
    "cas": "",
    "image": "/images/other.png",
    "imageLabel": "Illustrative category photograph",
    "description": "Nitrosol is part of the Hussain & Co product list. Send your required specification, quantity, and destination for a quotation.",
    "applications": [],
    "moq": "Confirm with quotation",
    "sdsUrl": "",
    "tdsUrl": "",
    "featured": false,
    "order": 68
  },
  {
    "slug": "potassium-carbonate",
    "name": "Potassium Carbonate",
    "category": "other",
    "grade": "Confirm with our team",
    "purity": "Specification on request",
    "packaging": "On request",
    "origin": "Confirm with quotation",
    "needsConfirmation": false,
    "cas": "",
    "image": "/images/other.png",
    "imageLabel": "Illustrative category photograph",
    "description": "Potassium Carbonate is part of the Hussain & Co product list. Send your required specification, quantity, and destination for a quotation.",
    "applications": [],
    "moq": "Confirm with quotation",
    "sdsUrl": "",
    "tdsUrl": "",
    "featured": false,
    "order": 69
  },
  {
    "slug": "potassium-hydroxide",
    "name": "Potassium Hydroxide",
    "category": "other",
    "grade": "Confirm with our team",
    "purity": "Specification on request",
    "packaging": "On request",
    "origin": "Confirm with quotation",
    "needsConfirmation": false,
    "cas": "",
    "image": "/images/other.png",
    "imageLabel": "Illustrative category photograph",
    "description": "Potassium Hydroxide is part of the Hussain & Co product list. Send your required specification, quantity, and destination for a quotation.",
    "applications": [],
    "moq": "Confirm with quotation",
    "sdsUrl": "",
    "tdsUrl": "",
    "featured": false,
    "order": 70
  },
  {
    "slug": "citric-acid",
    "name": "Citric Acid",
    "category": "other",
    "grade": "Confirm with our team",
    "purity": "Specification on request",
    "packaging": "On request",
    "origin": "Confirm with quotation",
    "needsConfirmation": false,
    "cas": "",
    "image": "/images/other.png",
    "imageLabel": "Illustrative category photograph",
    "description": "Citric Acid is part of the Hussain & Co product list. Send your required specification, quantity, and destination for a quotation.",
    "applications": [],
    "moq": "Confirm with quotation",
    "sdsUrl": "",
    "tdsUrl": "",
    "featured": false,
    "order": 71
  },
  {
    "slug": "boric-acid",
    "name": "Boric Acid",
    "category": "other",
    "grade": "Confirm with our team",
    "purity": "Specification on request",
    "packaging": "On request",
    "origin": "Confirm with quotation",
    "needsConfirmation": false,
    "cas": "",
    "image": "/images/other.png",
    "imageLabel": "Illustrative category photograph",
    "description": "Boric Acid is part of the Hussain & Co product list. Send your required specification, quantity, and destination for a quotation.",
    "applications": [],
    "moq": "Confirm with quotation",
    "sdsUrl": "",
    "tdsUrl": "",
    "featured": false,
    "order": 72
  },
  {
    "slug": "sulphur-elemental",
    "name": "Sulphur Elemental",
    "category": "other",
    "grade": "Confirm with our team",
    "purity": "Specification on request",
    "packaging": "On request",
    "origin": "Confirm with quotation",
    "needsConfirmation": false,
    "cas": "",
    "image": "/images/other.png",
    "imageLabel": "Illustrative category photograph",
    "description": "Sulphur Elemental is part of the Hussain & Co product list. Send your required specification, quantity, and destination for a quotation.",
    "applications": [],
    "moq": "Confirm with quotation",
    "sdsUrl": "",
    "tdsUrl": "",
    "featured": false,
    "order": 73
  },
  {
    "slug": "maleic-anhydrous",
    "name": "Maleic Anhydrous",
    "category": "other",
    "grade": "Confirm with our team",
    "purity": "Specification on request",
    "packaging": "On request",
    "origin": "Confirm with quotation",
    "needsConfirmation": false,
    "cas": "",
    "image": "/images/other.png",
    "imageLabel": "Illustrative category photograph",
    "description": "Maleic Anhydrous is part of the Hussain & Co product list. Send your required specification, quantity, and destination for a quotation.",
    "applications": [],
    "moq": "Confirm with quotation",
    "sdsUrl": "",
    "tdsUrl": "",
    "featured": false,
    "order": 74
  },
  {
    "slug": "pathalic-anhydrous",
    "name": "Pathalic Anhydrous",
    "category": "other",
    "grade": "Confirm with our team",
    "purity": "Specification on request",
    "packaging": "On request",
    "origin": "Confirm with quotation",
    "needsConfirmation": false,
    "cas": "",
    "image": "/images/other.png",
    "imageLabel": "Illustrative category photograph",
    "description": "Pathalic Anhydrous is part of the Hussain & Co product list. Send your required specification, quantity, and destination for a quotation.",
    "applications": [],
    "moq": "Confirm with quotation",
    "sdsUrl": "",
    "tdsUrl": "",
    "featured": false,
    "order": 75
  }
];
